module.exports = {
    CHARACTER_MAPPER : {
        BANJO: '73-Banjo&Kazooie.json',
        get BANJOANDKAZOOIE(){ return this.BANJO },
        BAYO: '63-Bayonetta.json'
    },
    ULTIMATE_CHARACTERS : {        
        BANJO: {
            dataFiles: ['73-Banjo&Kazooie.json'],
            uriComponent: "banjo_and_kazooie",
            movePrefix: "Banjo_Kazooie",
            uniqueMoves: {
                "UPSPECIAL": "ShockSpringJump",
                "SHOCKSPRINGJUMP": "ShockSpringJump",
                "SPRINGJUMP": "ShockSpringJump",
                "SIDESPECIAL": "Wonderwing",
                "WONDERWING": "Wonderwing",
                "DOWNSPECIAL": "RearEgg",
                "REAREGG": "RearEgg",
                "NEUTRALSPECIAL": "EggFiring_PNG",
                "EGGFIRING": "EggFiring_PNG",
            }
        },
        get BANJOANDKAZOOIE(){
            return this.BANJO
        },
        get BAYO() {
            return this.BAYONETTA
        },
        BAYONETTA: {
            uriComponent: "bayonetta",
            movePrefix: "Bayonetta",
            uniqueMoves: {
                "FTILT1": "FTilt1",
                "FTILT2": "FTilt2",
                "FTILT3": "FTilt3",
                "FAIR1": "FAir1",
                "FAIR2": "FAir2",
                "FAIR3": "FAir3",
                "UPSPECIAL": "WitchTwistG",
                "WITCHTWIST": "WitchTwistG",
                "AIRWITCHTWIST": "WitchTwistA",
                "WITCHTWISTAIR": "WitchTwistA",
                "SIDESPECIAL": "HeelSlide",
                "HEELSLIDE": "HeelSlide",
                "SIDEB2": "HeelSlideEnd",
                "SIDESPECIAL2": "HeelSlideEnd",
                "AIRSIDESPECIAL": "AfterburnerKickUp",
                "AIRSIDEB": "AfterburnerKickUp",
                "DOWNSPECIAL": "WitchTime",
                "WITCHTIME": "WitchTime",
                "NEUTRALSPECIAL": "BulletClimax",
                "BULLETCLIMAX": "BulletClimax",
            }
        },
        BOWSER: {
            uriComponent: "bowser",
        },
        get SERG(){
            return this.BOWSER
        },
        get "BOWSER JR"() {
            return this.BOWSERJR
        },
        BOWSERJR: {
            uriComponent: "bowser_jr",
        }       
    },

    MOVE_LIST : {
        "JAB": "Jab1",
        "JAB1": "Jab1",
        "JAB2": "Jab2",
        "JAB3": "Jab3",
        "RAPIDJAB": "JabRapid",
        "RAPIDJABFINISH": "JabRapidEnd",
        "FTILT": "FTilt",
        "FORWARDTILT": "FTilt",
        "SIDETILT": "FTilt",
        "FTILTUP": "FTiltUp",
        "FORWARDTILTUP": "FTiltUp",
        "SIDETILTUP": "FTiltUp",
        "FTILTDOWN": "FTiltDown",
        "FORWARDTILTDOWN": "FTiltDown",
        "SIDETILTDOWN": "FTiltDown",
        "UTILT": "UTilt",
        "UPTILT": "UTilt",
        "DTILT": "DTilt",
        "DOWNTILT": "DTilt",
        "DASHATTACK": "DashAttack",
        "FSMASH": "FSmash",
        "FORWARDSMASH": "FSmash",
        "SIDESMASH": "FSmash",
        "DSMASH": "DSmash",
        "DOWNSMASH": "DSmash",
        "USMASH": "USmash",
        "UPSMASH": "USmash",
        "NEUTRALAIR": "NAir",
        "NAIR": "NAir",
        "FORWARDAIR": "FAir",
        "FAIR": "FAir",
        "BACKAIR": "BAir",
        "BAIR": "BAir",
        "RESIDUAL": "BAir",
        "RESIDUALDAMAGE": "BAir",
        "UPAIR": "UAir",
        "UAIR": "UAir",
        "DOWNAIR": "DAir",
        "DAIR": "DAir",
        "GRAB": "Grab",
        "DASHGRAB": "DashGrab",
        "RUNGRAB": "DashGrab",
        "RUNNINGGRAB": "DashGrab",
        "PIVOTGRAB": "PivotGrab",
        "TURNAROUNDGRAB": "PivotGrab",
        "PUMMEL": "Pummel",
        "GRABPUMMEL": "Pummel",
        "FORWARDTHROW": "FThrow",
        "FORWARDSTHROW": "FThrow",
        "FTHROW": "FThrow",
        "BACKTHROW": "BThrow",
        "BACKWARDSTHROW": "BThrow",
        "BTHROW": "BThrow",
        "UPTHROW": "UThrow",
        "UTHROW": "UThrow",
        "DOWNTHROW": "DThrow",
        "DTHROW": "DThrow",
        /* Special moves that you gotta look up by the character */
        "NEUTRALB":"NEUTRALSPECIAL",
        "NEUTRAL-B":"NEUTRALSPECIAL",
        "NEUTRALSPECIAL":"NEUTRALSPECIAL",
        "NEUTRAL-SPECIAL":"NEUTRALSPECIAL",
        "SIDEB":"SIDESPECIAL",
        "SIDE-B":"SIDESPECIAL",
        "SIDESPECIAL":"SIDESPECIAL",
        "SIDE-SPECIAL":"SIDESPECIAL",
        "BACKB":"BACKSPECIAL",
        "BACK-B":"BACKSPECIAL",
        "BACKSPECIAL":"BACKSPECIAL",
        "BACK-SPECIAL":"BACKSPECIAL",
        "UPB":"UPSPECIAL",
        "UP-B":"UPSPECIAL",
        "UPSPECIAL":"UPSPECIAL",
        "UP-SPECIAL":"UPSPECIAL",
        "DOWNB":"DOWNSPECIAL",
        "DOWN-B":"DOWNSPECIAL",
        "DOWNSPECIAL":"DOWNSPECIAL",
        "DOWN-SPECIAL":"DOWNSPECIAL",
    },

    GENERIC_MOVE_ALIASES_UFD : { //Visuals can be more specific than frame data. Ftilt-up shows ftilt-up but generic Ftilt frame data
        "Jab 1": "Jab1",
        "Jab 2": "Jab2",
        "Jab 3": "Jab3",
        "Rapid Jab": "JabRapid",
        "Rapid Finisher": "JabRapidEnd",
        "F-Tilt": "FTilt",
        "U-Tilt": "UTilt",
        "D-Tilt ": "DTilt",
        "Dash Attack": "DashAttack",
        "F-Smash ": "FSmash",
        "D-Smash": "DSmash",
        "U-Smash": "USmash",
        "N-Air": "NAir",
        "F-Air": "FAir",
        "B-Air": "BAir",
        "U-Air": "UAir",
        "D-Air": "DAir",
        "Grab": "Grab",
        "Dash Grab": "DashGrab",
        "Pivot Grab": "PivotGrab",
        "Pummel": "Pummel",
        "Forward Throw": "FThrow",
        "Back Throw": "BThrow",
        "Up Throw": "UThrow",
        "Down Throw": "DThrow"
    },

    INTERNAL_MOVE_ALIASES : { //What do people normally call these moves?

    }
}