const characterData = require('.././data');

module.exports = {
    BANJO: characterData.BanjoAndKazooie,
    get BANJOANDKAZOOIE(){ return this.BANJO },
    BAYO: characterData.Bayonetta,
    get BAYONETTA(){ return this.BAYO },
    get DARYN() {return this.BAYO },
    BOWSER: characterData.Bowser,
    get SERG(){ return this.BOWSER },
    BOWSERJR: characterData.BowserJr,
    BYLETH: characterData.Byleth,
    CAPTAINFALCON: characterData.CaptainFalcon,
    get FALCON(){ return this.CAPTAINFALCON },
    CHROM: characterData.Chrom,
    CLOUD: characterData.Cloud,
    CORRIN: characterData.Corrin,
    DAISY: characterData.Daisy,
    DARKPIT: characterData.DarkPit,
    DARKSAMUS: characterData.DarkSamus,
    DIDDYKONG: characterData.DiddyKong,
    get DIDDY(){ return this.DIDDYKONG },
    DONKEYKONG: characterData.DonkeyKong,
    get DK(){ return this.DONKEYKONG },
    DRMARIO: characterData.DrMario,
    get DOC() {return this.DRMARIO},
    DUCKHUNT: characterData.DuckHunt,
    get DUCKHUNTDOG(){ return this.DUCKHUNT },
    FALCO: characterData.Falco,
    get TOMMY(){ return this.FALCO },
    get SIRTHOMASGANON(){ return this.FALCO },
    FOX: characterData.Fox,
    GANONDORF: characterData.Ganondorf,
    get GANON(){ return this.GANONDORF },
    GRENINJA: characterData.Greninja,
    get GREN() { return this.GRENINJA },
    HERO: characterData.Hero,
    ICECLIMBERS: characterData.IceClimbers,
    get IC() {return this.ICECLIMBERS },
    get ICs() {return this.ICECLIMBERS },
    IKE: characterData.Ike,
    INCINEROAR: characterData.Incineroar,
    get BRYAN(){ return this.INCINEROAR },
    INKLING: characterData.Inkling,
    ISABELLE: characterData.Isabelle,
    JIGGLYPUFF: characterData.Jigglypuff,
    get JIGGS() {return this.JIGGLYPUFF},
    get PUFF(){ return this.JIGGLYPUFF},
    JOKER: characterData.Joker,
    KEN: characterData.Ken,
    get XAVIER() {return this.KEN},
    KINGDEDEDE: characterData.KingDedede,
    get DDD() {return this.KINGDEDEDE},
    get D3() {return this.KINGDEDEDE},
    get DeDeDe() {return this.KINGDEDEDE},
    get KingDDD() {return this.KINGDEDEDE},
    KINGKROOL: characterData.KingKRool,
    get KROOL() {return this.KINGKROOL},
    KIRBY: characterData.Kirby,
    LINK: characterData.Link,
    get DWAYNE(){ return this.LINK },
    LITTLEMAC: characterData.LittleMac,
    get LILMAC() {return this.LITTLEMAC},
    get MAC() {return this.LITTLEMAC },
    LUCARIO: characterData.Lucario,
    LUCAS: characterData.Lucas,
    get C(){ return this.LUCAS },
    LUCINA: characterData.Lucina,
    LUIGI: characterData.Luigi,
    MARIO: characterData.Mario,
    MARTH: characterData.Marth,
    get CHAZ() {return this.MARTH },
    MEGAMAN: characterData.MegaMan,
    METAKNIGHT: characterData.MetaKnight,
    MEWTWO: characterData.Mewtwo,
    get MEW2(){ return this.MEWTWO},
    get MIDTIER() {return this.MEWTWO },
    MIIBRAWLER: characterData.MiiBrawler,
    get BRAWLER() {return this.MIIBRAWLER},
    MIIGUNNER: characterData.MiiGunner,
    get GUNNER() {return this.MIIGUNNER},
    MIISWORDFIGHTER: characterData.MiiSwordfighter,
    get SWORDFIGHTER(){ return this.MIISWORDFIGHTER},
    get MIISWORD(){ return this.MIISWORDFIGHTER },
    MINMIN: characterData.MinMin,
    MRGAMEANDWATCH: characterData.MrGameAndWatch,
    get GW(){ return this.MRGAMEANDWATCH},
    get GAMEANDWATCH() {return this.MRGAMEANDWATCH},
    NESS: characterData.Ness,
    OLIMAR: characterData.Olimar,
    PACMAN: characterData.Pacman,
    PALUTENA: characterData.Palutena,
    get PALU(){ return this.PALUTENA},
    PEACH: characterData.Peach,
    PICHU: characterData.Pichu,
    PIKACHU: characterData.Pikachu,
    get PIKA(){ return this.PIKACHU},
    PIRANHAPLANT: characterData.PiranhaPlant,
    get PPLANT(){ return this.PIRANHAPLANT },
    PIT: characterData.Pit,
    SQUIRTLE: characterData.Squirtle,
    IVYSAUR: characterData.Ivysaur,
    CHARIZARD: characterData.Charizard,
    RICHTER: characterData.Richter,
    RIDLEY: characterData.Ridley,
    ROB: characterData.Rob,
    ROBIN: characterData.Robin,
    ROSALINA: characterData.RosalinaAndLuma,
    get ROSA(){return this.ROSALINA},
    ROY: characterData.Roy,
    RYU: characterData.Ryu,
    SAMUS: characterData.Samus,
    get BONESAW(){ return this.SAMUS },
    get ANTHONY(){ return this.SAMUS },
    SHEIK: characterData.Sheik,
    SHULK: characterData.Shulk,
    SIMON: characterData.Simon,
    get DANNY(){ return this.SIMON },
    SNAKE: characterData.Snake,
    SONIC: characterData.Sonic,
    TERRY: characterData.Terry,
    TOONLINK: characterData.ToonLink,
    get TLINK() {return this.TOONLINK},
    get TINK() {return this.TOONLINK},
    VILLAGER: characterData.Villager,
    WARIO: characterData.Wario,
    WIIFITTRAINER: characterData.WiiFitTrainer,
    get WIIFIT() {return this.WIIFITTRAINER},
    WOLF: characterData.Wolf,
    YOSHI: characterData.Yoshi,
    YOUNGLINK: characterData.YoungLink,
    get YLINK(){ return this.YOUNGLINK},
    get YINK(){ return this.YOUNGLINK},
    ZELDA: characterData.Zelda,
    ZEROSUITSAMUS: characterData.ZeroSuitSamus,
    get ZSS() {return this.ZEROSUITSAMUS}
}