const characterData = require('.././data');

CreateCharacterData = (characterInit) => {
    const charData = characterInit;
    if(charData == null){
        return null;
    }
    const moveMappings = charData.moveMappings;
    if(moveMappings == null){
        return charData;
    }
    let logicalName, key;
    moveMappings.forEach(
        moveMapping => {
            key = Object.keys(moveMapping)[0];
            logicalName = moveMapping[key];
            if(logicalName != null){
                charData.moves[key] = charData.moves[logicalName];
                charData.moves[key].Name = logicalName;
            }            
        }
    );    
    return charData;
}

module.exports = {
    get BANJO(){ return CreateCharacterData(characterData.BanjoAndKazooie) },
    get BANJOANDKAZOOIE(){ return this.BANJO },        
    get BAYO(){ return CreateCharacterData(characterData.Bayonetta ) },
    get BAYONETTA(){ return this.BAYO },
    get DARYN() {return this.BAYO },
    BOWSER: characterData.Bowser,
    get SERG(){ return this.BOWSER },
    BOWSERJR: characterData.BowserJr,
    BYLETH: characterData.Byleth,
    CAPTAINFALCON: characterData.CaptainFalcon,
    get FALCON(){ return this.CAPTAINFALCON },
    CHROM: characterData.Chrom,
    CLOUD: characterData.Cloud,
    CORRIN: characterData.Corrin,
    DAISY: characterData.Daisy,
    DARKPIT: characterData.DarkPit,
    DARKSAMUS: characterData.DarkSamus,
    DIDDYKONG: characterData.DiddyKong,
    get DIDDY(){ return this.DIDDYKONG },
    DONKEYKONG: characterData.DonkeyKong,
    get DK(){ return this.DONKEYKONG },
    DRMARIO: characterData.DrMario,
    get DOC() {return this.DRMARIO},
    DUCKHUNT: characterData.DuckHunt,
    get DUCKHUNTDOG(){ return this.DUCKHUNT },
    FALCO: characterData.Falco,
    get TOMMY(){ return this.FALCO },
    get SIRTHOMASGANON(){ return this.FALCO },
    FOX: characterData.Fox,
    GANONDORF: characterData.Ganondorf,
    get GANON(){ return this.GANONDORF },
    GRENINJA: characterData.Greninja,
    get GREN() { return this.GRENINJA },
    HERO: characterData.Hero,
    ICECLIMBERS: characterData.IceClimbers,
    get IC() {return this.ICECLIMBERS },
    get ICs() {return this.ICECLIMBERS },
    IKE: characterData.Ike,
    INCINEROAR: characterData.Incineroar,
    get BRYAN(){ return this.INCINEROAR },
    INKLING: characterData.Inkling,
    ISABELLE: characterData.Isabelle,
    JIGGLYPUFF: characterData.Jigglypuff,
    get JIGGS() {return this.JIGGLYPUFF},
    get PUFF(){ return this.JIGGLYPUFF},

    get JOKER() { return CreateCharacterData(characterData.Joker) },
    get ARSENE() { return CreateCharacterData(characterData.Arsene) },
    get KEN() { return CreateCharacterData(characterData.Ken) },
    get XAVIER() {return this.KEN},
    get KINGDEDEDE() { return CreateCharacterData(characterData.KingDedede) },
    get DDD() {return this.KINGDEDEDE},
    get D3() {return this.KINGDEDEDE},
    get DeDeDe() {return this.KINGDEDEDE},
    get KingDDD() {return this.KINGDEDEDE},
    get KINGKROOL() { return CreateCharacterData(characterData.KingKRool) },
    get KROOL() {return this.KINGKROOL},
    get KIRBY() { return CreateCharacterData(characterData.Kirby) },
    get LINK() { return CreateCharacterData(characterData.Link) },
    get DWAYNE(){ return this.LINK },
    get LITTLEMAC() { return CreateCharacterData(characterData.LittleMac) },
    get LILMAC() {return this.LITTLEMAC},
    get MAC() {return this.LITTLEMAC },
    get LUCARIO() { return CreateCharacterData(characterData.LittleMac) },
    get LUCAS() { return CreateCharacterData(characterData.Lucas) },
    get C(){ return this.LUCAS },
    LUCINA: characterData.Lucina,
    LUIGI: characterData.Luigi,
    MARIO: characterData.Mario,
    MARTH: characterData.Marth,
    get CHAZ() {return this.MARTH },
    MEGAMAN: characterData.MegaMan,
    METAKNIGHT: characterData.MetaKnight,
    MEWTWO: characterData.Mewtwo,
    get MEW2(){ return this.MEWTWO},
    get MIDTIER() {return this.MEWTWO },
    MIIBRAWLER: characterData.MiiBrawler,
    get BRAWLER() {return this.MIIBRAWLER},
    MIIGUNNER: characterData.MiiGunner,
    get GUNNER() {return this.MIIGUNNER},
    MIISWORDFIGHTER: characterData.MiiSwordfighter,
    get SWORDFIGHTER(){ return this.MIISWORDFIGHTER},
    get MIISWORD(){ return this.MIISWORDFIGHTER },
    get MINMIN(){ return CreateCharacterData(characterData.MinMin ) },
    MRGAMEANDWATCH: characterData.MrGameAndWatch,
    get GW(){ return this.MRGAMEANDWATCH},
    get GAMEANDWATCH() {return this.MRGAMEANDWATCH},
    NESS: characterData.Ness,
    OLIMAR: characterData.Olimar,
    get ZAPBRANNIGAN(){ return this.OLIMAR },
    PACMAN: characterData.Pacman,
    PALUTENA: characterData.Palutena,
    get PALU(){ return this.PALUTENA},
    PEACH: characterData.Peach,
    PICHU: characterData.Pichu,
    PIKACHU: characterData.Pikachu,
    get PIKA(){ return this.PIKACHU},
    PIRANHAPLANT: characterData.PiranhaPlant,
    get PPLANT(){ return this.PIRANHAPLANT },
    PIT: characterData.Pit,
    SQUIRTLE: characterData.Squirtle,
    IVYSAUR: characterData.Ivysaur,
    CHARIZARD: characterData.Charizard,
    RICHTER: characterData.Richter,
    RIDLEY: characterData.Ridley,
    ROB: characterData.Rob,
    ROBIN: characterData.Robin,
    ROSALINA: characterData.RosalinaAndLuma,
    get ROSA(){return this.ROSALINA},
    ROY: characterData.Roy,
    RYU: characterData.Ryu,
    SAMUS: characterData.Samus,
    get BONESAW(){ return this.SAMUS },
    get ANTHONY(){ return this.SAMUS },
    SHEIK: characterData.Sheik,
    SHULK: characterData.Shulk,
    SIMON: characterData.Simon,
    get DANNY(){ return this.SIMON },
    SNAKE: characterData.Snake,
    SONIC: characterData.Sonic,
    TERRY: characterData.Terry,
    TOONLINK: characterData.ToonLink,
    get TLINK() {return this.TOONLINK},
    get TINK() {return this.TOONLINK},
    VILLAGER: characterData.Villager,
    WARIO: characterData.Wario,
    WIIFITTRAINER: characterData.WiiFitTrainer,
    get WIIFIT() {return this.WIIFITTRAINER},
    WOLF: characterData.Wolf,
    YOSHI: characterData.Yoshi,
    YOUNGLINK: characterData.YoungLink,
    get YLINK(){ return this.YOUNGLINK},
    get YINK(){ return this.YOUNGLINK},
    ZELDA: characterData.Zelda,
    ZEROSUITSAMUS: characterData.ZeroSuitSamus,
    get ZSS() {return this.ZEROSUITSAMUS}
}